# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conduit < Formula
  desc "Local-first, provider-aware terminal agent (Claude Code wire-compatible)."
  homepage "https://github.com/Icehunter/conduit"
  version "1.4.1"
  license "MIT OR Apache-2.0"

  on_macos do
    url "https://github.com/Icehunter/conduit/releases/download/v1.4.1/conduit_darwin_all.tar.gz"
    sha256 "7ed2420b56dd33b81491e8145c255f1b27e4bc3266a66fba8e5acee90337430c"

    define_method(:install) do
      bin.install "conduit"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Icehunter/conduit/releases/download/v1.4.1/conduit_linux_amd64.tar.gz"
      sha256 "ab24fe14da063f7c8c4c00f23565d0aa7a11bf6bce569b9871c85e0a1e4377df"
      define_method(:install) do
        bin.install "conduit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Icehunter/conduit/releases/download/v1.4.1/conduit_linux_arm64.tar.gz"
      sha256 "c4db3c90d78173e542b71bac76aaf5abdb57d3ce1d9ca9ecc9daa008a4911db1"
      define_method(:install) do
        bin.install "conduit"
      end
    end
  end

  test do
    system "#{bin}/conduit version"
  end
end
