# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Conduit < Formula
  desc "Local-first, provider-aware terminal agent (Claude Code wire-compatible)."
  homepage "https://github.com/Icehunter/conduit"
  version "1.11.0"
  license "MIT OR Apache-2.0"

  on_macos do
    url "https://github.com/Icehunter/conduit/releases/download/v1.11.0/conduit_darwin_all.tar.gz"
    sha256 "4c6f8065ad52ca8fe18ea9eb5b369263fb0ae93e09847c8d710ea53da90b8f57"

    define_method(:install) do
      bin.install "conduit"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Icehunter/conduit/releases/download/v1.11.0/conduit_linux_amd64.tar.gz"
      sha256 "f095b913d65d36da744a4ea02f1ee45bf449d96b0be54573eed77c282711a233"
      define_method(:install) do
        bin.install "conduit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Icehunter/conduit/releases/download/v1.11.0/conduit_linux_arm64.tar.gz"
      sha256 "2ea521de14cc9523bbf7d4d125451dfa7591373362e20bbe804cd61fa8534e28"
      define_method(:install) do
        bin.install "conduit"
      end
    end
  end

  test do
    system "#{bin}/conduit version"
  end
end
