# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DuneAdmin < Formula
  desc "Local-first, provider-aware terminal agent (Claude Code wire-compatible)."
  homepage "https://github.com/Icehunter/dune-admin"
  version "0.23.0"
  license "MIT"

  on_macos do
    url "https://github.com/Icehunter/dune-admin/releases/download/v0.23.0/dune-admin_darwin_all.tar.gz"
    sha256 "6c358704f51f314a75c836df1013a40e14a31f0a84787946c8c1831105cad4e1"

    define_method(:install) do
      bin.install "dune-admin"
      pkgshare.install "item-data.json"
      pkgshare.install "quality-data.json"
      pkgshare.install "tags-data.json"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Icehunter/dune-admin/releases/download/v0.23.0/dune-admin_linux_amd64.tar.gz"
      sha256 "e51b9e67ba03876ad084ad396056c2e76bab398c2f6556392ec5adf05dc7bfb9"
      define_method(:install) do
        bin.install "dune-admin"
        pkgshare.install "item-data.json"
        pkgshare.install "quality-data.json"
        pkgshare.install "tags-data.json"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Icehunter/dune-admin/releases/download/v0.23.0/dune-admin_linux_arm64.tar.gz"
      sha256 "9d60703a3ea39ecf43b7ebf687886b46039a0e2a129c0c8175f5ac9d906328bd"
      define_method(:install) do
        bin.install "dune-admin"
        pkgshare.install "item-data.json"
        pkgshare.install "quality-data.json"
        pkgshare.install "tags-data.json"
      end
    end
  end

  test do
    system "#{bin}/dune-admin version"
  end
end
