# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DuneAdmin < Formula
  desc "Local-first, provider-aware terminal agent (Claude Code wire-compatible)."
  homepage "https://github.com/Icehunter/dune-admin"
  version "0.27.0"
  license "MIT"

  on_macos do
    url "https://github.com/Icehunter/dune-admin/releases/download/v0.27.0/dune-admin_darwin_all.tar.gz"
    sha256 "66010c8a67d1dda5e4259e6274e3fb14a06a5870d4ad40aad8d33a0063b1c8d5"

    define_method(:install) do
      bin.install "dune-admin"
      pkgshare.install "item-data.json"
      pkgshare.install "quality-data.json"
      pkgshare.install "tags-data.json"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Icehunter/dune-admin/releases/download/v0.27.0/dune-admin_linux_amd64.tar.gz"
      sha256 "ef3ee2eaea219f6a3a5735a3b3d054f13fc96177ab86b1f90308db4fecd3e453"
      define_method(:install) do
        bin.install "dune-admin"
        pkgshare.install "item-data.json"
        pkgshare.install "quality-data.json"
        pkgshare.install "tags-data.json"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Icehunter/dune-admin/releases/download/v0.27.0/dune-admin_linux_arm64.tar.gz"
      sha256 "612b0b23d97481ad612cf019c1e00765b5f1ce98e745cf29c845e958585ee94e"
      define_method(:install) do
        bin.install "dune-admin"
        pkgshare.install "item-data.json"
        pkgshare.install "quality-data.json"
        pkgshare.install "tags-data.json"
      end
    end
  end

  test do
    system "#{bin}/dune-admin version"
  end
end
